---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmsgaas-app
  namespace: mmsgaas
  labels:
    app: mmsgaas-app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mmsgaas-app
  template:
    metadata:
      labels:
        app: mmsgaas-app
    spec:
      containers:
        - 
          env:
            - name: AMQ_USR
              valueFrom:
                secretKeyRef:
                  key: spring.artemis.user
                  name: mmsgaas-app
            - name: AMQ_PWD
              valueFrom:
                secretKeyRef:
                  key: spring.artemis.password
                  name: mmsgaas-app
            - name: SRV_PORT
              valueFrom:
                configMapKeyRef:
                  name: mmsgaas-app
                  key: server.port
            - name: AMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: spring.artemis.host
                  name: mmsgaas-app
            - name: AMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: spring.artemis.port
                  name: mmsgaas-app
            - name: AMQ_QUEU
              valueFrom:
                configMapKeyRef:
                  key: jms.queue
                  name: mmsgaas-app
          image: cloops/mmsgaas-app:v0.10
          name: mmsgaas-app
          imagePullPolicy: Always
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 1000Mi
              cpu: 400m
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mmsgaas-app
  namespace: mmsgaas
  labels:
    app: mmsgaas-app
spec:
  selector:
    app: mmsgaas-app
  ports:
  - name: mmsgaas-app
    port: 38080
    targetPort: 8888
    protocol: TCP
  type: LoadBalancer
