---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mmsgaas-app
  namespace: mmsgaas
  labels:
    app: mmsgaas-app
spec:
  rules:
    - host: "restapi.cloud.mmsgaas"
      http:
        paths:
        - pathType: Prefix
          path: "/send"
          backend:
            service:
              name: mmsgaas-app
              port: 
               number: 38080
