---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mmsgaas-bus
  namespace: mmsgaas
  labels:
    app: mmsgaas-bus
spec:
  rules:
    - host: dashboard.cloud.mmsgaas
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mmsgaas-bus
                port: 
                  number: 8161
